var res = {
    HelloWorld_png : "res/HelloWorld.png",
    BG :  'res/images/bg.jpg' ,
    BG_Front_png : 'res/images/bgFront.png',
    BG_SelectCar_png : 'res/images/BgSelectStyle.png',
    BG_HowTo_png : 'res/images/BgHowTo.png',
    BG_Menu_png :  'res/images/BgMenu.png' ,
    BG_GameOver_png :  'res/images/BgGameOver.png',
    Button_pressAny_bf_png : "res/images/pressAnyButton_before.png",
    Button_pressAny_af_png : "res/images/pressAnyButton_after.png",
    Button_arrowLeft_bf_png : "res/images/arrow_black_left.png",
    Button_arrowLeft_af_png : "res/images/arrow_black_left_invert.png",
    Button_arrowRight_bf_png : "res/images/arrow_black_right.png",
    Button_arrowRight_af_png : "res/images/arrow_black_right_invert.png",
    Button_restart_png : "res/images/restart.png",
    Button_restart_invert_png : "res/images/restart_invert.png",
    Button_start_png : "res/images/startButton.png",
    Button_start_invert_png : "res/images/startButton_invert.png",
    Button_select_png : "res/images/selectButton.png",
    Button_select_invert_png : "res/images/selectButton_invert.png",
    Button_selectCar_png : "res/images/selectCarButton.png",
    Button_selectCar_invert_png : "res/images/selectCarButton_invert.png",
    Button_howToPlay_png : "res/images/howToPlayButton.png",
    Button_howToPlay_invert_png : "res/images/howToPlayButton_invert.png",
    Sprite_Car_01 : "res/images/Car_01.png",
    Sprite_Car_02 : "res/images/Car_02.png",
    Sprite_Car_03 : "res/images/Car_03.png",
    Sprite_Car_04 : "res/images/Car_04.png",
    Sprite_Car_05 : "res/images/Car_05.png",
    Sprite_Car_06 : "res/images/Car_06.png",
    Sprite_Car_07 : "res/images/Car_07.png",
    Sprite_Car_08 : "res/images/Car_08.png",
    Sprite_Car_09 : "res/images/Car_09.png",
    Obstacle_01 : 'res/images/obstacle_01.png',
    Sound_GTR : 'res/sound/r35.mp3',
    Sound_GameOver : 'res/sound/GameOver.mp3',
};

var g_resources = [];
for (var i in res) {
    g_resources.push(res[i]);
}
